namespace :add_games do
  desc "Add inital games to database"
  task seed: :environment do
  	xbox = Console.find_or_create_by(name: "XB1")
		playstation = Console.find_or_create_by(name: "PS4")

  	bf = Game.find_or_create_by(name: "Battlefield: Hardline")
  	bl = Game.find_or_create_by(name: "Borderlands: The Handsome Collection")
  	cd = Game.find_or_create_by(name: "Call of Duty: Advanced Warfare")
  	ds = Game.find_or_create_by(name: "Destiny")
  	ev = Game.find_or_create_by(name: "Evolve")
  	fc = Game.find_or_create_by(name: "Farcry 4")
  	fi = Game.find_or_create_by(name: "Fifa 15")
  	fo  = Game.find_or_create_by(name: "Forza 5")
  	gta = Game.find_or_create_by(name: "Grand Theft Auto V")
  	hl = Game.find_or_create_by(name: "Halo: The Master Chief Collection")
  	mkx = Game.find_or_create_by(name: "Mortal Kombat X")
  	mad = Game.find_or_create_by(name: "Madden 15")
  	nba = Game.find_or_create_by(name: "NBA 2k15")
  	pc = Game.find_or_create_by(name: "Project Cars")
  	ti = Game.find_or_create_by(name: "Titanfall")
  	wwe = Game.find_or_create_by(name: "WWE 2k15")
  	mlb = Game.find_or_create_by(name: "MLB 15: The Show")

	  ConsolesGame.find_or_create_by(console: xbox, game: bf)
	  ConsolesGame.find_or_create_by(console: xbox, game: bl)
	  ConsolesGame.find_or_create_by(console: xbox, game: cd)
	  ConsolesGame.find_or_create_by(console: xbox, game: ds)
	  ConsolesGame.find_or_create_by(console: xbox, game: ev)
	  ConsolesGame.find_or_create_by(console: xbox, game: fc)
	  ConsolesGame.find_or_create_by(console: xbox, game: fi)
	  ConsolesGame.find_or_create_by(console: xbox, game: fo)
	  ConsolesGame.find_or_create_by(console: xbox, game: gta)
	  ConsolesGame.find_or_create_by(console: xbox, game: hl)
	  ConsolesGame.find_or_create_by(console: xbox, game: mkx)
	  ConsolesGame.find_or_create_by(console: xbox, game: mad)
	  ConsolesGame.find_or_create_by(console: xbox, game: nba)
	  ConsolesGame.find_or_create_by(console: xbox, game: pc)
	  ConsolesGame.find_or_create_by(console: xbox, game: ti)
	  ConsolesGame.find_or_create_by(console: xbox, game: wwe)

	  ConsolesGame.find_or_create_by(console: playstation, game: bf)
	  ConsolesGame.find_or_create_by(console: playstation, game: bl)
	  ConsolesGame.find_or_create_by(console: playstation, game: cd)
	  ConsolesGame.find_or_create_by(console: playstation, game: ds)
	  ConsolesGame.find_or_create_by(console: playstation, game: ev)
	  ConsolesGame.find_or_create_by(console: playstation, game: fc)
	  ConsolesGame.find_or_create_by(console: playstation, game: fi)
	  ConsolesGame.find_or_create_by(console: playstation, game: fo)
	  ConsolesGame.find_or_create_by(console: playstation, game: gta)
	  ConsolesGame.find_or_create_by(console: playstation, game: mlb)
	  ConsolesGame.find_or_create_by(console: playstation, game: mkx)
	  ConsolesGame.find_or_create_by(console: playstation, game: mad)
	  ConsolesGame.find_or_create_by(console: playstation, game: nba)
	  ConsolesGame.find_or_create_by(console: playstation, game: pc)
	  ConsolesGame.find_or_create_by(console: playstation, game: ti)
	  ConsolesGame.find_or_create_by(console: playstation, game: wwe)


  end
end